# Generated by Django 3.2 on 2021-04-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Merchants',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('frg', 'Fragile'), ('lqd', 'Liquid')], default='frg', max_length=10)),
                ('invoice_id', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=100, unique=True)),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('order_datetime', models.DateField(auto_now_add=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_order', to='parcel.merchant')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
